spring:
  application:
    name: my_pet_app

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate



